Persona.create(:id => 1,:ci => 4114230, :nombre => 'Andres Percy', :apaterno => 'Chavez', :amaterno => 'Ortuno', :sexo => 'MASCULINO', :profesion_id =>1,:universidad_id => 65, :cargo_id => 3, :tipo_id => 3)
Persona.create(:id => 2,:ci => 1111111, :nombre => 'Jimena', :apaterno => 'Barrientos', :amaterno => 'Eduardo', :sexo => 'FEMENINO', :profesion_id =>1,:universidad_id => 65, :cargo_id => 3, :tipo_id => 3)
Persona.create(:id => 3,:ci => 2222222, :nombre => 'Laura', :apaterno => 'Barrientos', :amaterno => 'Eduardo', :sexo => 'FEMENINO', :profesion_id =>1,:universidad_id => 65, :cargo_id => 3, :tipo_id =>3)
CuentaCorreo.create(:correoe => 'andres.chavex@gmail.com', :persona_id => 1)
CuentaCorreo.create(:correoe => 'andres19x@hotmail.com', :persona_id => 1)
CuentaCorreo.create(:correoe => 'coordinacionscr@gmail.com', :persona_id => 2)
CuentaCorreo.create(:correoe => 'promocioncemla@gmail.com', :persona_id => 3)