Universidad.find_or_create_by_id(1, :nombre=> 'Universidad Autónoma del Beni José Ballivián', :abreviacion => 'UABJB', :ciudad_id => 4, :tipo => 'PUBLICA' )
Universidad.find_or_create_by_id(2, :nombre=> 'Universidad Privada del Valle', :abreviacion => 'UNIVALLE', :ciudad_id =>4, :tipo => 'PRIVADA' )
Universidad.find_or_create_by_id(3, :nombre=> 'Universidad Mayor de San Simón', :abreviacion => 'UMSS', :ciudad_id =>2, :tipo => 'PUBLICA' )
Universidad.find_or_create_by_id(4, :nombre=> 'Escuela Militar de Ingeniería', :abreviacion => 'EMI', :ciudad_id =>2, :tipo => 'PRIVADA' )
Universidad.find_or_create_by_id(5, :nombre=> 'Universidad Simón I. Patiño', :abreviacion => 'USIP', :ciudad_id =>2, :tipo => 'PRIVADA' )
Universidad.find_or_create_by_id(6, :nombre=> 'Universidad Central', :abreviacion => 'UNICEN', :ciudad_id =>2, :tipo => 'PRIVADA' )
Universidad.find_or_create_by_id(7, :nombre=> 'Universidad Católica Boliviana San Pablo', :abreviacion => 'UCB', :ciudad_id =>2, :tipo => 'PRIVADA' )
Universidad.find_or_create_by_id(8, :nombre=> 'Uni. Priv. de Cs. Administrativas y Tecnológicas', :abreviacion => 'UCATEC', :ciudad_id =>2, :tipo => 'PRIVADA' )
Universidad.find_or_create_by_id(9, :nombre=> 'Universidad de Aquino Bolivia', :abreviacion => 'UDABOL', :ciudad_id =>2, :tipo => 'PRIVADA' )
Universidad.find_or_create_by_id(10, :nombre=> 'Universidad Adventista de Bolivia', :abreviacion => 'UAB', :ciudad_id =>2, :tipo => 'PRIVADA' )
Universidad.find_or_create_by_id(11, :nombre=> 'Universidad Privada Abierta Latinoamericana', :abreviacion => 'UPAL', :ciudad_id =>2, :tipo => 'PRIVADA' )
Universidad.find_or_create_by_id(12, :nombre=> 'Universidad Privada Boliviana', :abreviacion => 'UPB', :ciudad_id =>2, :tipo => 'PRIVADA' )
Universidad.find_or_create_by_id(13, :nombre=> 'Universidad Privada del Valle', :abreviacion => 'UNIVALLE', :ciudad_id =>2, :tipo => 'PRIVADA' )
Universidad.find_or_create_by_id(14, :nombre=> 'Universidad Privada Franz Tamayo', :abreviacion => 'UNIFRANZ', :ciudad_id =>2, :tipo => 'PRIVADA' )
Universidad.find_or_create_by_id(15, :nombre=> 'Universidad Técnica Privada Cosmos', :abreviacion => 'UNITEPC', :ciudad_id =>2, :tipo => 'PRIVADA' )
Universidad.find_or_create_by_id(16, :nombre=> 'Universidad Mayor de San Andrés', :abreviacion => 'UMSA', :ciudad_id =>3, :tipo => 'PUBLICA' )
Universidad.find_or_create_by_id(17, :nombre=> 'Universidad Pública de El Alto', :abreviacion => 'UPEA', :ciudad_id =>3, :tipo => 'PUBLICA' )
Universidad.find_or_create_by_id(18, :nombre=> 'Escuela Militar de Ingeniería', :abreviacion => 'EMI', :ciudad_id =>3, :tipo => 'PRIVADA' )
Universidad.find_or_create_by_id(19, :nombre=> 'Universidad Católica Boliviana San Pablo', :abreviacion => 'UCB', :ciudad_id =>3, :tipo => 'PRIVADA' )
Universidad.find_or_create_by_id(20, :nombre=> 'Universidad Central', :abreviacion => 'UNICEN', :ciudad_id =>3, :tipo => 'PRIVADA' )
Universidad.find_or_create_by_id(21, :nombre=> 'Universidad de Aquino Bolivia', :abreviacion => 'UDABOL', :ciudad_id =>3, :tipo => 'PRIVADA' )
Universidad.find_or_create_by_id(22, :nombre=> 'Universidad Privada Boliviana', :abreviacion => 'UPB', :ciudad_id =>3, :tipo => 'PRIVADA' )
Universidad.find_or_create_by_id(23, :nombre=> 'Universidad Privada del Valle', :abreviacion => 'UNIVALLE', :ciudad_id =>3, :tipo => 'PRIVADA' )
Universidad.find_or_create_by_id(24, :nombre=> 'Universidad Privada Franz Tamayo', :abreviacion => 'UNIFRANZ', :ciudad_id =>3, :tipo => 'PRIVADA' )
Universidad.find_or_create_by_id(25, :nombre=> 'Universidad La Salle', :abreviacion => 'ULS', :ciudad_id =>3, :tipo => 'PRIVADA' )
Universidad.find_or_create_by_id(26, :nombre=> 'Universidad Boliviana de Informática', :abreviacion => 'UBI', :ciudad_id =>3, :tipo => 'PRIVADA' )
Universidad.find_or_create_by_id(27, :nombre=> 'Universidad Nur', :ciudad_id => 3, :tipo => 'PRIVADA' )
Universidad.find_or_create_by_id(28, :nombre=> 'Universidad Loyola', :ciudad_id =>3, :tipo => 'PRIVADA' )
Universidad.find_or_create_by_id(29, :nombre=> 'Universidad Privada Nuestra Señora de La Paz', :abreviacion => 'UNSLP', :ciudad_id =>3, :tipo => 'PRIVADA' )
Universidad.find_or_create_by_id(30, :nombre=> 'Universidad Privada San Francisco de Asis', :abreviacion => 'USFA', :ciudad_id =>3, :tipo => 'PRIVADA' )
Universidad.find_or_create_by_id(31, :nombre=> 'Universidad Real', :abreviacion => 'UREAL', :ciudad_id =>3, :tipo => 'PRIVADA' )
Universidad.find_or_create_by_id(32, :nombre=> 'Universidad Salesiana de Bolivia', :abreviacion => 'USALESIANA', :ciudad_id =>3, :tipo => 'PRIVADA' )
Universidad.find_or_create_by_id(33, :nombre=> 'Universidad de los Andes', :abreviacion => 'UDELOSANDES', :ciudad_id =>3, :tipo => 'PRIVADA' )
Universidad.find_or_create_by_id(34, :nombre=> 'Universidad para la Investig. Estratégica en Bolivia', :abreviacion => 'UPIEB', :ciudad_id =>3, :tipo => 'PRIVADA' )
Universidad.find_or_create_by_id(35, :nombre=> 'Universidad Tecnológica Boliviana', :abreviacion => 'UTB', :ciudad_id =>3, :tipo => 'PRIVADA' )
Universidad.find_or_create_by_id(36, :nombre=> 'Universidad Unión Bolivariana', :abreviacion => 'UB', :ciudad_id =>3, :tipo => 'PRIVADA' )
Universidad.find_or_create_by_id(37, :nombre=> 'Universidad Saint Paul', :abreviacion => 'USP', :ciudad_id =>3, :tipo => 'PRIVADA' )
Universidad.find_or_create_by_id(38, :nombre=> 'Universidad de la Cordillera', :abreviacion => 'UCORDILLERA', :ciudad_id =>3, :tipo => 'PRIVADA' )
Universidad.find_or_create_by_id(39, :nombre=> 'Universidad Técnica de Oruro', :abreviacion => 'UTO', :ciudad_id =>8, :tipo => 'PUBLICA' )
Universidad.find_or_create_by_id(40, :nombre=> 'Universidad de Aquino Bolivia', :abreviacion => 'UDABOL', :ciudad_id =>8, :tipo => 'PRIVADA' )
Universidad.find_or_create_by_id(41, :nombre=> 'Universidad Privada Abierta Latinoamericana', :abreviacion => 'UPAL', :ciudad_id =>8, :tipo => 'PRIVADA' )
Universidad.find_or_create_by_id(42, :nombre=> 'Universidad Privada De Oruro', :abreviacion => 'UNIOR', :ciudad_id =>8, :tipo => 'PRIVADA' )
Universidad.find_or_create_by_id(43, :nombre=> 'Universidad Amazónica de Pando', :abreviacion => 'UAP', :ciudad_id =>5, :tipo => 'PUBLICA' )
Universidad.find_or_create_by_id(44, :nombre=> 'Univ. Autónoma Gabriel Rene Moreno', :abreviacion => 'UAGRM', :ciudad_id =>6, :tipo => 'PUBLICA' )
Universidad.find_or_create_by_id(45, :nombre=> 'Escuela Militar de Ingeniería', :abreviacion => 'EMI', :ciudad_id =>6, :tipo => 'PRIVADA' )
Universidad.find_or_create_by_id(46, :nombre=> 'Universidad Nacional del Oriente', :abreviacion => 'UNO', :ciudad_id =>6, :tipo => 'PRIVADA' )
Universidad.find_or_create_by_id(47, :nombre=> 'Univ. Nac. Ecológica Santa Cruz', :abreviacion => 'UECOLOGICA', :ciudad_id =>6, :tipo => 'PRIVADA' )
Universidad.find_or_create_by_id(48, :nombre=> 'Universidad Católica Boliviana San Pablo', :ciudad_id => 6, :tipo => 'PRIVADA' )
Universidad.find_or_create_by_id(49, :nombre=> 'Universidad Cristiana de Bolivia', :abreviacion => 'UCEBOL', :ciudad_id =>6, :tipo => 'PRIVADA' )
Universidad.find_or_create_by_id(50, :nombre=> 'Universidad Empresarial Mateo Kuljis', :ciudad_id =>6, :tipo => 'PRIVADA' )
Universidad.find_or_create_by_id(51, :nombre=> 'Universidad Evangélica Boliviana' , :abreviacion => 'UEB', :ciudad_id =>6, :tipo => 'PRIVADA' )
Universidad.find_or_create_by_id(52, :nombre=> 'Universidad Nur', :ciudad_id =>6, :tipo => 'PRIVADA' )
Universidad.find_or_create_by_id(53, :nombre=> 'Universidad Privada Cumbre', :ciudad_id =>6, :tipo => 'PRIVADA' )
Universidad.find_or_create_by_id(54, :nombre=> 'Universidad Priv. de Aquino Bolivia', :abreviacion => 'UDABOL', :ciudad_id =>6, :tipo => 'PRIVADA' )
Universidad.find_or_create_by_id(55, :nombre=> 'Universidad Bethesda', :abreviacion => 'UNIBETH', :ciudad_id =>6, :tipo => 'PRIVADA' )
Universidad.find_or_create_by_id(56, :nombre=> 'Univ. Priv. de Sta. Cruz de la Sierra', :abreviacion => 'UPSA', :ciudad_id =>6, :tipo => 'PRIVADA' )
Universidad.find_or_create_by_id(57, :nombre=> 'Universidad Privada Domingo Savio', :abreviacion => 'UPDS', :ciudad_id =>6, :tipo => 'PRIVADA' )
Universidad.find_or_create_by_id(58, :nombre=> 'Universidad Priv. Franz Tamayo', :abreviacion => 'UNIFRANZ', :ciudad_id =>6, :tipo => 'PRIVADA' )
Universidad.find_or_create_by_id(59, :nombre=> 'Univ. Salesiana de Bolivia', :abreviacion => 'USALESIANA', :ciudad_id =>6, :tipo => 'PRIVADA' )
Universidad.find_or_create_by_id(60, :nombre=> 'Univ. Tecnológica Priv. de Sta. Cruz', :abreviacion => 'UTEPSA', :ciudad_id =>6, :tipo => 'PRIVADA' )
Universidad.find_or_create_by_id(61, :nombre=> 'Universidad Autónoma Tomás Frías', :abreviacion => 'UATF', :ciudad_id =>7, :tipo => 'PUBLICA' )
Universidad.find_or_create_by_id(62, :nombre=> 'Universidad Nacional Siglo XX', :abreviacion => 'UNSXX', :ciudad_id =>7, :tipo => 'PUBLICA' )
Universidad.find_or_create_by_id(63, :nombre=> 'Universidad Autónoma Juan Misael Saracho', :abreviacion => 'UAJMS', :ciudad_id =>9, :tipo => 'PUBLICA' )
Universidad.find_or_create_by_id(64, :nombre=> 'Universidad Católica Boliviana San Pablo - Tarija', :ciudad_id =>9, :tipo => 'PRIVADA' )
Universidad.find_or_create_by_id(65, :nombre=> 'Universidad Mayor de San Francisco Xavier', :abreviacion => 'USFX', :ciudad_id =>1, :tipo => 'PUBLICA' )
Universidad.find_or_create_by_id(66, :nombre=> 'Universidad Andina Simón Bolívar', :abreviacion => 'UASB', :ciudad_id =>1, :tipo => 'PUBLICA' )
Universidad.find_or_create_by_id(67, :nombre=> 'Universidad Privada del Valle', :abreviacion => 'UNIVALLE', :ciudad_id =>1, :tipo => 'PRIVADA' )
Universidad.find_or_create_by_id(68, :nombre=> 'Universidad Boliviana de Informática', :abreviacion => 'UBI', :ciudad_id =>1, :tipo => 'PRIVADA' )
